# -*- coding: utf-8 -*-
"""CodeAlpha_Iris_Flower_Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsbnukDXUBmoFY8mshnAxGII7zaf12NA
"""

print("hello,data science")

print("najmeen khan")

a=10
b=20
print(a+b)

"""1.python output"""

print("hello world")

print("I am tired")

print(9876)

print("najmeen",45,96,False ,sep='/')

print("najmeen",end='-')
print("khan")

"""2.Data Types"""

#integer
print(45)

#decimal/float
print(4.56)

#boolean
print(True)
print(False)

#string
print("najmeen khan")

#complex
print(5+6j)

#list
print([1,2,3,4,5])

#tuple
print((1,2,3))

#set
print({1,2,3})

#dictionary
print({'name':'najmeen','surname':'khan'})

#type
type(45)

"""3.Variables"""

name='najmeen'
print(name)

a=3
b=4
print(a+b)

# Dynamic Typing
a=5
# Static Typing
int a=5

# Dynamic Binding
a=5
print(a)
a="najmeen"
print(a)

# Static Binding
int a=5

a,b,c=45,96,44
print(a,b,c)

a=b=c=45
print(a,b,c)

"""4. Keywords & Identifiers"""

#keywords

#identifiers

"""5.User Input"""

input('your name')

"""6. Type Conversion"""

# implicit

print(type(5),type(4.5))
print(5+4.5)

# explicit
int('45')

type(int(45))

# take input from the users and store them in variables
a= input('enter the first no.')
b= input('enter the second no.')
result=int (a)+ int (b)
print(result)

"""7. Literals

* Operator in Python
"""

# Arithmetic operators
print(5+ 6)
print(5- 6)
print(5* 6)
print(5/ 6)
print(5// 6)
print(5% 6)
print(5** 6)

# Relational Operators
print(5> 6)
print(5< 6)
print(5>= 6)
print(5<= 6)
print(5== 6)
print(5!= 6)

# Logical Operator
print(0 and 1)
print(1 or 0)

# Bitwise Operators
print(2 & 3)
print(2 | 3)
print(2 ^ 3)
print(~3)
print(4 >> 2)
print(5 << 2)

# Assignment Operators

a = 2
a += 3
print(a)
a -= 3
print(a)
a *= 3
print(a)
a /= 3
print(a)
a %= 3
print(a)

# Membership Operators
# in/ not in
print('D' in 'Delhi')
print('D' not in 'Delhi')

# program - Find the sum of a 3 digit number entered by the user
number=345
a=number%10
print(a)
number=number//10
b=number%10
print(b)
number=number//10
c=number%10
print(c)
print(a+b+c)

"""If - else in Python"""

email = input('enter email')
password = input('enter password')

if email == 'najmeen' and password == '1234':
  print('verified')
elif email == 'najmeen' and password != '1234':
  print('not verified')
  password = input('enter password again')
  if password == '1234':
    print('verified')
  else:
    print('beta tumse na ho paayega')
else:
  print('not verified')

# minimal in 3 numbers
a = int(input('enter first number'))
b = int(input('enter second number'))
c = int(input('enter third number'))
if a<b and a<c:
  print('smallest is',a)
elif b<c:
  print('smallest is',b)
else:
  print('smallest is',c)

# Menu driven calculator

num1= int(input('enter first number'))
num2= int(input('enter second number'))
op = input('enter the operation')
if op=='+':
   print(num1+num2)

elif op=='-':
  print(num1-num2)
elif op=='*':
   print(num1*num2)
else:
   print(num1/num2)

# Menu driven atm
menu=input("""how can I help you Najmeen
1.enter 1 for pin change
2.enter 2 for balance check
3.enter 3 for withdraw
4.enter 4 for exit""")
if menu =='1':
    print('pin change')
elif menu=='2':
    print('balance check')
elif menu=='3':
    print('withdraw')
else:
    print('exit')

"""Module in Python
* math
* keyword
* random
* datetime
"""

#math
import math

math.factorial(5)
math.log(6)

#keyword
import keyword

print(keyword.kwlist)

#random
import random

print(random.randint(1,100))

#datetime
import datetime

print(datetime.datetime.now())

"""Loops in Python

 * Need for loop
 * While loop
 * For loop
"""

number = int(input('enter a number'))
i=0
while i<11:
  print(number* i)
  i +=1

"""* While"""

# generate a random integer between 1 and 100
import random
jackpot = random.randint(1,100)

guess = int (input('guess kro'))
counter = 1
while guess != jackpot:
  if guess < jackpot:
    print('galt ! guess higher')
  else:
    print('galt! guess lower')

  guess = int(input('guess kro'))
  counter +=1
else:
    print('correct guess')
    print('attempt',counter)

"""* For"""

# For loop

for i in range(1,11):

    print(i)

for i in range(1,50,2):
  print(i)

for i in 'najmeenkhan':
  print(i)

"""Program- The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. You have to write a program to find out the population at the end of each of the last 10 years."""

current_pop = 10000
for i in range(10,0,-1):
  print(i,current_pop)
  current_pop=current_pop / 1.1

"""* Sequence sum
 1/1! + 2/2! + 3/3! + .....
"""



n = int(input('enter n'))
result = 0
fact = 1
for i in range(1,n+1):
  fact= fact * i
  result = result + i/fact
  print(result)

"""* Nested Loops"""

# unque pairs
for i in range(1,5):
  for j in range(1,5):
    print(i,j)

"""* Pattern 1"""

rows = int(input('enter the number of rows'))

for i in range(1,rows+1):
  print('*')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Step 2: Iris Dataset ko load karein
df = sns.load_dataset('iris')

# Data ka pehla 5 rows dekhne ke liye
df.head()

# 1. Features (X) aur Target (y) ko alag karein
X = df.drop(columns=['species'])  # species ko chhodkar baaki saare columns X hain
y = df['species']                 # species column humara y (target) hai

# 2. Data ko Train aur Test sets mein baantein (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Check karne ke liye ki data sahi se split hua ya nahi
print("Training data ka size:", X_train.shape)
print("Testing data ka size:", X_test.shape)

# 1. Model ka ek object/instance banayein
model = RandomForestClassifier(random_state=42)

# 2. Model ko Train karein (X_train aur y_train ka use karke)
model.fit(X_train, y_train)

# 3. Ab test data (X_test) par predictions nikaalein
y_pred = model.predict(X_test)

# 4. Accuracy check karein ki model ne kitna sahi jawab diya
accuracy = accuracy_score(y_test, y_pred)
print(f"Model ki Accuracy hai: {accuracy * 100:.2f}%")

# 5. Detail report dekhne ke liye
print("\nClassification Report:")
print(classification_report(y_test, y_pred))